### ISSUE TITLE
Edge cases and unexpected paths for copy

### ISSUE THREAD

**Issue by mroz22** [trezor/trezor-onboarding#3]
- [ ] recovery T1 with mnemonic lower than 24 words, both flows, success and error (wrong word)
- [ ] when installing fw, error occurs in download phase
- [ ] when installing fw, error occurs in erase/upload phase
- [ ] when installing T1 / T2, different messages after successful install
- [ ] when searching for device takes more than 15 seconds in "searching for device" screen
- [ ] pgp signature only for selected installers in bridge step
- [ ] unexpected state bootloader - for example in PIN step, when user connects device in bootloader #26 
- [ ] unexpected state different device - for example in PIN step, when user connects different device #28 
- [ ] unexpected state device disconnected - for example in PIN step, when user disconnects device #27
